package GUI_CHIDO;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import Clases.DatabaseConnection;
import Clases.BackgroundPanel;
import Clases.Cliente;
import java.awt.Font;
import java.awt.Color;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.MediaTracker;
import java.util.logging.Level;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableCellEditor;
import javax.swing.AbstractCellEditor;
import javax.swing.JTable;
import java.awt.Component;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;

/**
 *
 * @author ASUS
 */
public class ContratosActivos extends javax.swing.JFrame {

    private JFrame parentFrame;
    private DefaultTableModel tableModel; // Declare tableModel
    private int currentClienteId; // New field to store the logged-in client ID
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ContratosActivos.class.getName());

    // Declarar el BackgroundPanel. Los otros componentes (jButton2, jScrollPane1, jTable1)
    // son declarados automáticamente en la sección "variables declaration" por el Form Editor.
    private BackgroundPanel backgroundPanel;


    /**
     * Creates new form ContratosActivos
     * @param parentFrame The parent JFrame to return to.
     * @param loggedInCliente The Cliente object of the currently logged-in user.
     */
    public ContratosActivos(JFrame parentFrame, Cliente loggedInCliente) { // <-- Este es el constructor que espera dos argumentos
        this.parentFrame = parentFrame;
        // Check if loggedInCliente is null (e.g., if opened directly from main for testing)
        if (loggedInCliente != null) {
            this.currentClienteId = loggedInCliente.getIdCliente();
        } else {
            // Handle case where no client is logged in, e.g., for testing purposes
            this.currentClienteId = -1; // Or some default/error value
            JOptionPane.showMessageDialog(null, "No se ha proporcionado un ID de cliente. Se mostrarán todos los contratos (solo para desarrollo).", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        
        initComponents();
        this.setSize(800, 600); // Set a larger initial size for the frame
        this.setLocationRelativeTo(null); // Center the frame
        
        // Add ComponentListener for responsiveness
        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                adjustComponentPositions();
            }
        });

        // Load data into the table
        loadContractsData();
        adjustComponentPositions(); // Adjust positions initially
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        // Inicializar BackgroundPanel como content pane
        backgroundPanel = new BackgroundPanel("/Imagenes/fondo.png");
        backgroundPanel.setLayout(null); // Usar null layout para posicionamiento absoluto
        this.setContentPane(backgroundPanel); // Establecer como content pane

        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Contratos Activos"); // Título de la ventana

        // Button Regresar
        jButton2.setBackground(new Color(90, 150, 200)); // Azul suave
        jButton2.setFont(new Font("Segoe UI", Font.BOLD, 18)); // Fuente más moderna
        jButton2.setForeground(Color.WHITE);
        
        // Cargar y escalar el icono si existe
        try {
            ImageIcon atrasIcon = new ImageIcon(getClass().getResource("/Imagenes/Atras.png"));
            if (atrasIcon.getImageLoadStatus() == MediaTracker.COMPLETE) {
                Image img = atrasIcon.getImage();
                Image scaledImg = img.getScaledInstance(30, 30, Image.SCALE_SMOOTH); // Escalar icono
                jButton2.setIcon(new ImageIcon(scaledImg));
            } else {
                logger.log(Level.WARNING, "Imagen 'Atras.png' no encontrada. Usando solo texto para el botón Regresar.");
            }
        } catch (Exception e) {
            logger.log(Level.WARNING, "Error al cargar la imagen 'Atras.png': " + e.getMessage());
        }
        
        jButton2.setText("Regresar");
        jButton2.setContentAreaFilled(false); // Mantener transparente para ver el fondo
        jButton2.setBorderPainted(false); // No pintar borde por defecto
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        backgroundPanel.add(jButton2); // Añadir a backgroundPanel

        // Table Model Setup
        String[] columnNames = {"ID Contrato", "ID Cliente", "Fecha Inicio", "Fecha Fin", "Monto Total", "Tipo Servicio", "Estado Pago", "Acción"};
        tableModel = new DefaultTableModel(new Object[][]{}, columnNames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 7; // Solo la columna de Acción es editable para el botón
            }
        };
        jTable1.setModel(tableModel);
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14)); // Fuente para encabezado
        jTable1.getTableHeader().setBackground(new Color(173, 216, 230)); // Light blue header
        jTable1.getTableHeader().setForeground(new Color(30, 50, 70)); // Texto oscuro para encabezado
        jTable1.setRowHeight(25);
        jTable1.setFillsViewportHeight(true); // Make table fill the scroll pane
        jTable1.setBackground(new Color(240, 248, 255)); // Alice Blue background for table (celeste muy claro)
        jTable1.setForeground(new Color(50, 50, 50)); // Dark text color
        jTable1.setSelectionBackground(new Color(150, 200, 230)); // Azul pastel para selección
        jTable1.setSelectionForeground(Color.WHITE); // Texto blanco en selección

        jScrollPane1.setViewportView(jTable1);
        // La línea que causaba el error se moverá o se asegurará que se ejecute después de la inicialización
        // del componente. Si el error persiste, puede ser un problema de carga del .form.
        jScrollPane1.setBorder(BorderFactory.createLineBorder(new Color(180, 210, 230), 1)); // Borde pastel para el scroll pane
        backgroundPanel.add(jScrollPane1); // Añadir a backgroundPanel

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        if (parentFrame != null) {
            parentFrame.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Loads contract data from the database and populates the JTable.
     */
    private void loadContractsData() {
        // Clear existing data
        tableModel.setRowCount(0);

        try (Connection conn = DatabaseConnection.getConnection()) {
            String sql;
            PreparedStatement stmt;

            if (currentClienteId != -1) { // If a valid client ID is provided, filter by it
                sql = "SELECT c.idContrato, c.Cliente_idCliente, c.fecha_inicio, c.fecha_fin, c.monto_total, c.tiposervicio, " +
                      "COALESCE(f.estado_pago, 'sin_factura') as estado_pago, " +
                      "CASE WHEN c.fecha_fin > CURDATE() THEN 'activo' ELSE 'vencido' END as estado " +
                      "FROM contrato c " +
                      "LEFT JOIN factura f ON c.idContrato = f.idFactura " +
                      "WHERE c.Cliente_idCliente = ? AND c.fecha_fin > CURDATE()";
                stmt = conn.prepareStatement(sql);
                stmt.setInt(1, currentClienteId);
            } else { // For testing or if no client ID is available, show all (or none)
                sql = "SELECT c.idContrato, c.Cliente_idCliente, c.fecha_inicio, c.fecha_fin, c.monto_total, c.tiposervicio, " +
                      "COALESCE(f.estado_pago, 'sin_factura') as estado_pago, " +
                      "CASE WHEN c.fecha_fin > CURDATE() THEN 'activo' ELSE 'vencido' END as estado " +
                      "FROM contrato c " +
                      "LEFT JOIN factura f ON c.idContrato = f.idFactura " +
                      "WHERE c.fecha_fin > CURDATE()";
                stmt = conn.prepareStatement(sql);
            }
            
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                Object[] row = new Object[8]; // Aumentado a 8 columnas (incluyendo botón)
                row[0] = rs.getInt("idContrato");
                row[1] = rs.getInt("Cliente_idCliente");
                
                java.sql.Date fechaInicio = rs.getDate("fecha_inicio");
                java.sql.Date fechaFin = rs.getDate("fecha_fin");
                row[2] = fechaInicio;
                row[3] = fechaFin;
                row[4] = rs.getDouble("monto_total");
                row[5] = rs.getString("tiposervicio");
                
                // Estado de pago con formato amigable
                String estadoPago = rs.getString("estado_pago");
                switch (estadoPago) {
                    case "pagado":
                        row[6] = "✅ Pagado";
                        break;
                    case "pendiente":
                        row[6] = "⏳ Pendiente";
                        break;
                    case "sin_factura":
                        row[6] = "❌ Sin Factura";
                        break;
                    default:
                        row[6] = "❓ " + estadoPago;
                        break;
                }

                // Verificar si puede cancelar el contrato (mínimo 30 días desde inicio)
                long daysSinceStart = ChronoUnit.DAYS.between(
                    fechaInicio.toLocalDate(), 
                    LocalDate.now()
                );
                
                if (daysSinceStart >= 30) {
                    row[7] = "Cancelar";
                } else {
                    row[7] = "Sin tiempo mínimo (" + (30 - daysSinceStart) + " días restantes)";
                }

                tableModel.addRow(row);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los datos de contratos: " + e.getMessage(), "Error de Base de Datos", JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, "Error al cargar contratos", e);
        }
        
        // Configurar renderer y editor para la columna de acción
        jTable1.getColumn("Acción").setCellRenderer(new ButtonRenderer());
        jTable1.getColumn("Acción").setCellEditor(new ButtonEditor());
    }

    /**
     * Adjusts the position and size of components when the frame is resized.
     */
    private void adjustComponentPositions() {
        int newWidth = getContentPane().getWidth();
        int newHeight = getContentPane().getHeight();

        // Adjust jButton2 (Regresar)
        int buttonWidth = 200;
        int buttonHeight = 50;
        int buttonX = 20;
        int buttonY = 20;
        jButton2.setBounds(buttonX, buttonY, buttonWidth, buttonHeight);

        // Adjust jScrollPane1 (table)
        int tablePadding = 40; // Padding from edges
        int tableX = tablePadding;
        int tableY = buttonY + buttonHeight + 20; // Below the button with some gap
        int tableWidth = newWidth - (2 * tablePadding);
        int tableHeight = newHeight - tableY - tablePadding;
        jScrollPane1.setBounds(tableX, tableY, tableWidth, tableHeight);

        // Revalidate and repaint the panel
        backgroundPanel.revalidate();
        backgroundPanel.repaint();
    }

    /**
     * Cancela un contrato específico
     */
    private void cancelContract(int contractId) {
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro de que desea cancelar este contrato?\nEsta acción no se puede deshacer.",
            "Confirmar Cancelación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        if (confirm == JOptionPane.YES_OPTION) {
            try (Connection conn = DatabaseConnection.getConnection()) {
                String sql = "UPDATE contrato SET estado = 'cancelado', fecha_fin = CURDATE() WHERE idContrato = ?";
                PreparedStatement stmt = conn.prepareStatement(sql);
                stmt.setInt(1, contractId);
                
                int rowsAffected = stmt.executeUpdate();
                
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(
                        this,
                        "Contrato cancelado exitosamente.",
                        "Cancelación Exitosa",
                        JOptionPane.INFORMATION_MESSAGE
                    );
                    // Recargar la tabla
                    loadContractsData();
                } else {
                    JOptionPane.showMessageDialog(
                        this,
                        "No se pudo cancelar el contrato.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                    );
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(
                    this,
                    "Error al cancelar el contrato: " + e.getMessage(),
                    "Error de Base de Datos",
                    JOptionPane.ERROR_MESSAGE
                );
                logger.log(Level.SEVERE, "Error al cancelar contrato", e);
            }
        }
    }

    // Clase para renderizar botones en la tabla
    class ButtonRenderer extends JButton implements TableCellRenderer {
        public ButtonRenderer() {
            setOpaque(true);
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            setText((value == null) ? "" : value.toString());
            
            if (value != null && value.toString().equals("Cancelar")) {
                setBackground(new Color(220, 53, 69)); // Rojo para cancelar
                setForeground(Color.WHITE);
                setEnabled(true);
            } else {
                setBackground(Color.LIGHT_GRAY);
                setForeground(Color.DARK_GRAY);
                setEnabled(false);
            }
            
            return this;
        }
    }

    // Clase para editar botones en la tabla
    class ButtonEditor extends AbstractCellEditor implements TableCellEditor {
        private JButton button;
        private String label;
        private boolean isPushed;
        private int selectedRow;

        public ButtonEditor() {
            button = new JButton();
            button.setOpaque(true);
            button.addActionListener(e -> fireEditingStopped());
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value,
                boolean isSelected, int row, int column) {
            label = (value == null) ? "" : value.toString();
            button.setText(label);
            isPushed = true;
            selectedRow = row;
            
            if (label.equals("Cancelar")) {
                button.setBackground(new Color(220, 53, 69));
                button.setForeground(Color.WHITE);
            } else {
                button.setBackground(Color.LIGHT_GRAY);
                button.setForeground(Color.DARK_GRAY);
            }
            
            return button;
        }

        @Override
        public Object getCellEditorValue() {
            if (isPushed && label.equals("Cancelar")) {
                // Obtener el ID del contrato de la fila seleccionada
                int contractId = (Integer) tableModel.getValueAt(selectedRow, 0);
                cancelContract(contractId);
            }
            isPushed = false;
            return label;
        }

        @Override
        public boolean stopCellEditing() {
            isPushed = false;
            return super.stopCellEditing();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        // For standalone testing, you might pass a dummy Cliente or null
        java.awt.EventQueue.invokeLater(() -> new ContratosActivos(null, null).setVisible(true)); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
