package GUI_CHIDO;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel; // Import DefaultTableModel
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import Clases.DatabaseConnection; // Import DatabaseConnection
import Clases.BackgroundPanel; // Import BackgroundPanel
import Clases.Cliente; // Importar la clase Cliente
import java.awt.Font;
import java.awt.Color;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.JOptionPane; // Import JOptionPane for error messages
import javax.swing.ImageIcon; // Import ImageIcon
import java.awt.Image; // Import java.awt.Image
import java.awt.MediaTracker; // Import java.awt.MediaTracker
import java.util.logging.Level; // Import java.util.logging.Level
import javax.swing.BorderFactory; // Importar BorderFactory

/**
 *
 * @author ASUS
 */
public class ContratosActivos extends javax.swing.JFrame {

    private JFrame parentFrame;
    private DefaultTableModel tableModel; // Declare tableModel
    private int currentClienteId; // New field to store the logged-in client ID
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ContratosActivos.class.getName());

    // Declarar el BackgroundPanel. Los otros componentes (jButton2, jScrollPane1, jTable1)
    // son declarados automáticamente en la sección "variables declaration" por el Form Editor.
    private BackgroundPanel backgroundPanel;


    /**
     * Creates new form ContratosActivos
     * @param parentFrame The parent JFrame to return to.
     * @param loggedInCliente The Cliente object of the currently logged-in user.
     */
    public ContratosActivos(JFrame parentFrame, Cliente loggedInCliente) { // <-- Este es el constructor que espera dos argumentos
        this.parentFrame = parentFrame;
        // Check if loggedInCliente is null (e.g., if opened directly from main for testing)
        if (loggedInCliente != null) {
            this.currentClienteId = loggedInCliente.getIdCliente();
        } else {
            // Handle case where no client is logged in, e.g., for testing purposes
            this.currentClienteId = -1; // Or some default/error value
            JOptionPane.showMessageDialog(null, "No se ha proporcionado un ID de cliente. Se mostrarán todos los contratos (solo para desarrollo).", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        
        initComponents();
        this.setSize(800, 600); // Set a larger initial size for the frame
        this.setLocationRelativeTo(null); // Center the frame
        
        // Add ComponentListener for responsiveness
        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                adjustComponentPositions();
            }
        });

        // Load data into the table
        loadContractsData();
        adjustComponentPositions(); // Adjust positions initially
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        // Inicializar BackgroundPanel como content pane
        backgroundPanel = new BackgroundPanel("/Imagenes/fondo.png");
        backgroundPanel.setLayout(null); // Usar null layout para posicionamiento absoluto
        this.setContentPane(backgroundPanel); // Establecer como content pane

        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Contratos Activos"); // Título de la ventana

        // Button Regresar
        jButton2.setBackground(new Color(90, 150, 200)); // Azul suave
        jButton2.setFont(new Font("Segoe UI", Font.BOLD, 18)); // Fuente más moderna
        jButton2.setForeground(Color.WHITE);
        
        // Cargar y escalar el icono si existe
        try {
            ImageIcon atrasIcon = new ImageIcon(getClass().getResource("/Imagenes/Atras.png"));
            if (atrasIcon.getImageLoadStatus() == MediaTracker.COMPLETE) {
                Image img = atrasIcon.getImage();
                Image scaledImg = img.getScaledInstance(30, 30, Image.SCALE_SMOOTH); // Escalar icono
                jButton2.setIcon(new ImageIcon(scaledImg));
            } else {
                logger.log(Level.WARNING, "Imagen 'Atras.png' no encontrada. Usando solo texto para el botón Regresar.");
            }
        } catch (Exception e) {
            logger.log(Level.WARNING, "Error al cargar la imagen 'Atras.png': " + e.getMessage());
        }
        
        jButton2.setText("Regresar");
        jButton2.setContentAreaFilled(false); // Mantener transparente para ver el fondo
        jButton2.setBorderPainted(false); // No pintar borde por defecto
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        backgroundPanel.add(jButton2); // Añadir a backgroundPanel

        // Table Model Setup
        String[] columnNames = {"ID Contrato", "ID Cliente", "Fecha Inicio", "Fecha Fin", "Monto Total", "Tipo Servicio"};
        tableModel = new DefaultTableModel(new Object[][]{}, columnNames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Make all cells non-editable
            }
        };
        jTable1.setModel(tableModel);
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14)); // Fuente para encabezado
        jTable1.getTableHeader().setBackground(new Color(173, 216, 230)); // Light blue header
        jTable1.getTableHeader().setForeground(new Color(30, 50, 70)); // Texto oscuro para encabezado
        jTable1.setRowHeight(25);
        jTable1.setFillsViewportHeight(true); // Make table fill the scroll pane
        jTable1.setBackground(new Color(240, 248, 255)); // Alice Blue background for table (celeste muy claro)
        jTable1.setForeground(new Color(50, 50, 50)); // Dark text color
        jTable1.setSelectionBackground(new Color(150, 200, 230)); // Azul pastel para selección
        jTable1.setSelectionForeground(Color.WHITE); // Texto blanco en selección

        jScrollPane1.setViewportView(jTable1);
        // La línea que causaba el error se moverá o se asegurará que se ejecute después de la inicialización
        // del componente. Si el error persiste, puede ser un problema de carga del .form.
        jScrollPane1.setBorder(BorderFactory.createLineBorder(new Color(180, 210, 230), 1)); // Borde pastel para el scroll pane
        backgroundPanel.add(jScrollPane1); // Añadir a backgroundPanel

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        if (parentFrame != null) {
            parentFrame.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Loads contract data from the database and populates the JTable.
     */
    private void loadContractsData() {
        // Clear existing data
        tableModel.setRowCount(0);

        try (Connection conn = DatabaseConnection.getConnection()) {
            String sql;
            PreparedStatement stmt;

            if (currentClienteId != -1) { // If a valid client ID is provided, filter by it
                sql = "SELECT idContrato, Cliente_idCliente, fecha_inicio, fecha_fin, monto_total, tiposervicio FROM contrato WHERE Cliente_idCliente = ?";
                stmt = conn.prepareStatement(sql);
                stmt.setInt(1, currentClienteId);
            } else { // For testing or if no client ID is available, show all (or none)
                sql = "SELECT idContrato, Cliente_idCliente, fecha_inicio, fecha_fin, monto_total, tiposervicio FROM contrato";
                stmt = conn.prepareStatement(sql);
            }
            
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                Object[] row = new Object[6];
                row[0] = rs.getInt("idContrato");
                row[1] = rs.getInt("Cliente_idCliente");
                row[2] = rs.getDate("fecha_inicio");
                row[3] = rs.getDate("fecha_fin");
                row[4] = rs.getDouble("monto_total");
                row[5] = rs.getString("tiposervicio"); // Assuming tiposervicio is a String

                tableModel.addRow(row);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los datos de contratos: " + e.getMessage(), "Error de Base de Datos", JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, "Error al cargar contratos", e);
        }
    }

    /**
     * Adjusts the position and size of components when the frame is resized.
     */
    private void adjustComponentPositions() {
        int newWidth = getContentPane().getWidth();
        int newHeight = getContentPane().getHeight();

        // Adjust jButton2 (Regresar)
        int buttonWidth = 200;
        int buttonHeight = 50;
        int buttonX = 20;
        int buttonY = 20;
        jButton2.setBounds(buttonX, buttonY, buttonWidth, buttonHeight);

        // Adjust jScrollPane1 (table)
        int tablePadding = 40; // Padding from edges
        int tableX = tablePadding;
        int tableY = buttonY + buttonHeight + 20; // Below the button with some gap
        int tableWidth = newWidth - (2 * tablePadding);
        int tableHeight = newHeight - tableY - tablePadding;
        jScrollPane1.setBounds(tableX, tableY, tableWidth, tableHeight);

        // Revalidate and repaint the panel
        backgroundPanel.revalidate();
        backgroundPanel.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        // For standalone testing, you might pass a dummy Cliente or null
        java.awt.EventQueue.invokeLater(() -> new ContratosActivos(null, null).setVisible(true)); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
