/*
 * Click nbproject://SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbproject://SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_CHIDO;

import javax.swing.JFrame;

/**
 *
 * @author ASUS
 */
public class PBasic extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PBasic.class.getName());
    private JFrame parentFrame;

    /**
     * Creates new form PBasic
     */
    public PBasic() {
        initComponents();
    }

    public PBasic(JFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Plan Basico 300 mb promo.png")));
        jLabel1.setBounds(49, 107, 300, 256); // Estimated icon size; adjust if needed

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 36));
        jLabel2.setText("Plan Básico – 300 Mbps");
        jLabel2.setBounds(375, 35, 405, 57);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18));
        jLabel3.setText("Promoción “Empieza sin límites”");
        jLabel3.setBounds(435, 92, 283, 25);

        jLabel5.setText("📅 Primer mes a solo $10");
        jLabel5.setBounds(375, 169, 145, 16);

        jLabel6.setText("📶 Router Wi-Fi GRATIS");
        jLabel6.setBounds(375, 203, 145, 16);

        jLabel7.setText("💥 Instalación en menos de 24 horas SIN COSTO");
        jLabel7.setBounds(375, 237, 266, 16);

        jLabel8.setText("🎁 3 meses de soporte prioritario");
        jLabel8.setBounds(375, 271, 266, 16);

        jLabel9.setText("🟢 Perfecto para estudiantes, hogares pequeños o quienes recién empiezan en el mundo digital.");
        jLabel9.setBounds(95, 363, 521, 16);

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Contratar-removebg-preview (1).png")));
        jToggleButton1.setContentAreaFilled(false);
        jToggleButton1.setBounds(496, 305, 223, 70);

        jLabel10.setText("💨 300 Mbps ideales para navegar, redes sociales, videollamadas y streaming en HD");
        jLabel10.setBounds(375, 135, 455, 16);

        jLabel11.setText("💵 $20/mes – Potencia básica con gran velocidad a un precio accesible");
        jLabel11.setBounds(375, 289, 394, 16);

        jButton2.setBackground(new java.awt.Color(248, 243, 243));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 36));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atras.png")));
        jButton2.setText("Regresar");
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(evt -> jButton2ActionPerformed(evt));
        jButton2.setBounds(28, 35, 297, 60);

        add(jLabel1);
        add(jLabel2);
        add(jLabel3);
        add(jLabel5);
        add(jLabel6);
        add(jLabel7);
        add(jLabel8);
        add(jLabel9);
        add(jToggleButton1);
        add(jLabel10);
        add(jLabel11);
        add(jButton2);

        pack();
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
        if (parentFrame != null) {
            parentFrame.setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PBasic().setVisible(true));
    }

    // Variables declaration
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration
}