/*
 * Click nbproject://SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbproject://SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_CHIDO;

import javax.swing.JFrame;

/**
 *
 * @author ASUS
 */
public class PEstandar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PEstandar.class.getName());
    private JFrame parentFrame;

    /**
     * Creates new form PEstandar
     */
    public PEstandar() {
        initComponents();
    }

    public PEstandar(JFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLayout(null);

        jLabel8.setText("📶 Router Wi-Fi DUAL BAND incluido");
        jLabel8.setBounds(353, 289, 266, 16);

        jLabel9.setText("🟡 Ideal para familias con varios dispositivos y fanáticos del streaming.");
        jLabel9.setBounds(175, 363, 393, 16);

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Contratar-removebg-preview (1).png")));
        jToggleButton1.setText("jToggleButton1");
        jToggleButton1.setContentAreaFilled(false);
        jToggleButton1.addActionListener(evt -> jToggleButton1ActionPerformed(evt));
        jToggleButton1.setBounds(467, 307, 251, 67);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Plan Estandar promo.png")));
        jLabel1.setBounds(18, 101, 300, 256); // Estimated icon size; adjust if needed

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 36));
        jLabel2.setText("Plan Estándar – 500 Mbps");
        jLabel2.setBounds(331, 26, 447, 57);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18));
        jLabel3.setText("Promoción “Velocidad sin comparación”");
        jLabel3.setBounds(436, 83, 333, 25);

        jLabel5.setText("🔁 Cambia de proveedor y te damos 1 mes GRATIS");
        jLabel5.setBounds(353, 169, 279, 16);

        jLabel6.setText("🎁 Incluye 1 mes de acceso a Netflix o Disney+");
        jLabel6.setBounds(353, 203, 266, 16);

        jLabel7.setText("📞 Soporte técnico prioritario sin costo adicional");
        jLabel7.setBounds(353, 237, 266, 16);

        jLabel10.setText("💰 $35/mes – La combinación ideal entre potencia, estabilidad y ahorro");
        jLabel10.setBounds(353, 271, 390, 16);

        jLabel11.setText("📱 Transmisión fluida en HD y 4K, videoconferencias sin cortes, y juegos online con baja latencia");
        jLabel11.setBounds(353, 135, 455, 16);

        jButton2.setBackground(new java.awt.Color(248, 243, 243));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 36));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atras.png")));
        jButton2.setText("Regresar");
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(evt -> jButton2ActionPerformed(evt));
        jButton2.setBounds(0, 26, 297, 60);

        add(jLabel8);
        add(jLabel9);
        add(jToggleButton1);
        add(jLabel1);
        add(jLabel2);
        add(jLabel3);
        add(jLabel5);
        add(jLabel6);
        add(jLabel7);
        add(jLabel10);
        add(jLabel11);
        add(jButton2);

        pack();
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
        if (parentFrame != null) {
            parentFrame.setVisible(true);
        }
    }

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PEstandar().setVisible(true));
    }

    // Variables declaration
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration
}