/*
 * Click nbproject://SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbproject://SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_CHIDO;

import javax.swing.JFrame;

/**
 *
 * @author ASUS
 */
public class PlanTablos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PlanTablos.class.getName());
    private JFrame parentFrame;

    /**
     * Creates new form PlanTablos
     */
    public PlanTablos() {
        initComponents();
    }

    public PlanTablos(JFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLayout(null);

        jLabel8.setText("📲 App móvil para ver desde donde quieras");
        jLabel8.setBounds(66, 260, 378, 16);

        jLabel10.setText("💸 $10.99/mes – El plan básico más completo del mercado");
        jLabel10.setBounds(66, 291, 390, 16);

        jLabel12.setText("📺 100 canales – 40 en HD");
        jLabel12.setBounds(66, 162, 158, 16);

        jButton3.setBackground(new java.awt.Color(248, 243, 243));
        jButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 36));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atras.png")));
        jButton3.setText("Regresar");
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(evt -> jButton3ActionPerformed(evt));
        jButton3.setBounds(0, 26, 297, 60);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("✨ Ideal para quienes quieren lo justo y necesario, sin pagar de más.");
        jLabel13.setBounds(149, 360, 561, 16);

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Contratar-removebg-preview (1).png")));
        jToggleButton2.setText("jToggleButton1");
        jToggleButton2.setContentAreaFilled(false);
        jToggleButton2.addActionListener(evt -> jToggleButton2ActionPerformed(evt));
        jToggleButton2.setBounds(165, 309, 251, 67);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PlanEsencial.png")));
        jLabel4.setBounds(31, 94, 300, 256); // Assuming default icon size; adjust if needed

        jLabel14.setFont(new java.awt.Font("Segoe UI Historic", 1, 36));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Plan Esencial+");
        jLabel14.setBounds(331, 26, 447, 57);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Promoción: Primer mes GRATIS + 3 canales premium de regalo (cine, música, documentales)");
        jLabel15.setBounds(31, 86, 780, 25);

        jLabel16.setText("📰 Canales informativos, películas clásicas, contenido cultural");
        jLabel16.setBounds(66, 209, 279, 16);

        add(jLabel8);
        add(jLabel10);
        add(jLabel12);
        add(jButton3);
        add(jLabel13);
        add(jToggleButton2);
        add(jLabel4);
        add(jLabel14);
        add(jLabel15);
        add(jLabel16);

        pack();
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
        if (parentFrame != null) {
            parentFrame.setVisible(true);
        }
    }

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PlanTablos().setVisible(true));
    }

    // Variables declaration
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration
}