/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbproject://SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_CHIDO;

import javax.swing.JFrame;

/**
 *
 * @author ASUS
 */
public class PUltra extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PUltra.class.getName());
    private JFrame parentFrame;

    /**
     * Creates new form PUltra
     */
    public PUltra() {
        initComponents();
    }

    public PUltra(JFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLayout(null);

        jLabel5.setText("🏆 20% de descuento por 3 meses");
        jLabel5.setBounds(38, 234, 221, 16);

        jLabel6.setText("🚀 Velocidad garantizada o devolución parcial del pago");
        jLabel6.setBounds(38, 198, 420, 16);

        jLabel7.setText("🎮 Incluye 3 meses de Xbox Game Pass o Steam Wallet $10");
        jLabel7.setBounds(38, 162, 325, 16);

        jLabel8.setText("📞 Soporte técnico prioritario sin costo adicional");
        jLabel8.setBounds(38, 270, 420, 16);

        jLabel9.setText("🔴 Para gamers, streamers, y usuarios que necesitan el máximo rendimiento sin límites.");
        jLabel9.setBounds(169, 363, 465, 16);

        jButton2.setBackground(new java.awt.Color(248, 243, 243));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 36));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atras.png")));
        jButton2.setText("Regresar");
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(evt -> jButton2ActionPerformed(evt));
        jButton2.setBounds(27, 19, 297, 60);

        jToggleButton1.setText("jToggleButton1");
        jToggleButton1.setBounds(458, 306, 208, 67);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Plan Ultra.png")));
        jLabel1.setBounds(51, 85, 300, 278); // Assuming default icon size; adjust if needed

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 36));
        jLabel2.setText("Plan Ultra – 1 Gbps");
        jLabel2.setBounds(251, 19, 405, 57);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18));
        jLabel3.setText("Promoción “Conexión ÉPICA”");
        jLabel3.setBounds(304, 76, 283, 25);

        jLabel4.setText("💸 $60/mes – Tu hogar se transforma en un centro de alto rendimiento digital");
        jLabel4.setBounds(38, 306, 420, 16);

        jLabel10.setText("🎮 Juega en línea sin lag, transmite en vivo, descarga películas en segundos");
        jLabel10.setBounds(38, 126, 410, 16);

        add(jLabel5);
        add(jLabel6);
        add(jLabel7);
        add(jLabel8);
        add(jLabel9);
        add(jButton2);
        add(jToggleButton1);
        add(jLabel1);
        add(jLabel2);
        add(jLabel3);
        add(jLabel4);
        add(jLabel10);

        pack();
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
        if (parentFrame != null) {
            parentFrame.setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PUltra().setVisible(true));
    }

    // Variables declaration
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration
}