package GUI_CHIDO;

import Clases.BackgroundPanel;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.MediaTracker;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.logging.Level;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.SwingConstants;

/**
 *
 * @author ASUS
 */
public class Servicios extends javax.swing.JFrame {

    private JFrame parentFrame;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Servicios.class.getName());

    // Componentes de la interfaz de usuario
    private BackgroundPanel backgroundPanel; // Nuevo panel de fondo
    private javax.swing.JButton jButton1; // Regresar
    private javax.swing.JButton jButton4; // Telefonía Fija
    private javax.swing.JButton jButton7; // Telefonía Móvil
    private javax.swing.JButton jButton8; // Televisión
    private javax.swing.JButton jButton9; // Internet
    private javax.swing.JLabel jLabel1; // Título "Servicios"
    private javax.swing.JLabel jLabel3; // Etiqueta "Telefonía Móvil"
    private javax.swing.JLabel jLabel4; // Etiqueta "Telefonía Fija"
    private javax.swing.JLabel jLabel5; // Etiqueta "Televisión"
    private javax.swing.JLabel jLabel6; // Etiqueta "Internet"

    /**
     * Creates new form Servicios
     * @param parentFrame The parent JFrame to return to.
     */
    public Servicios(JFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
        this.setSize(600, 600); // Establecer el tamaño inicial
        this.setLocationRelativeTo(null); // Centrar la ventana

        // Add ComponentListener for responsiveness
        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                adjustComponentPositions();
            }
        });

        adjustComponentPositions(); // Ajustar posiciones inicialmente
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        // Inicialización del BackgroundPanel como content pane
        backgroundPanel = new BackgroundPanel("/Imagenes/fondo.png");
        backgroundPanel.setLayout(null); // Usamos un layout nulo para posicionamiento absoluto
        this.setContentPane(backgroundPanel); // Establecer como content pane

        // Inicialización de componentes
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Portafolio de Servicios"); // Título de la ventana más formal

        // Título "Servicios"
        jLabel1.setFont(new Font("Segoe UI", Font.BOLD, 32)); // Fuente ligeramente reducida
        jLabel1.setForeground(new Color(30, 50, 70)); // Azul oscuro-gris
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setText("PORTAFOLIO DE SERVICIOS"); // Texto más formal
        backgroundPanel.add(jLabel1);

        // Botón Regresar
        jButton1.setBackground(new Color(90, 150, 200)); // Azul suave
        jButton1.setFont(new Font("Segoe UI", Font.BOLD, 22)); // Fuente más grande
        jButton1.setForeground(Color.WHITE);
        
        // Cargar y escalar el icono si existe
        try {
            ImageIcon atrasIcon = new ImageIcon(getClass().getResource("/Imagenes/Atras.png"));
            if (atrasIcon.getImageLoadStatus() == MediaTracker.COMPLETE) {
                Image img = atrasIcon.getImage();
                Image scaledImg = img.getScaledInstance(50, 50, Image.SCALE_SMOOTH); // Escalar icono más grande
                jButton1.setIcon(new ImageIcon(scaledImg));
            } else {
                logger.log(Level.WARNING, "Imagen 'Atras.png' no encontrada. Usando solo texto para el botón Regresar.");
            }
        } catch (Exception e) {
            logger.log(Level.WARNING, "Error al cargar la imagen 'Atras.png': " + e.getMessage());
        }
        
        jButton1.setText("Regresar");
        jButton1.setContentAreaFilled(false); // Mantener transparente para ver el fondo
        jButton1.setBorderPainted(false); // No pintar borde por defecto
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(evt -> jButton1ActionPerformed(evt));
        backgroundPanel.add(jButton1);

        // Botones de servicio con iconos y texto
        // Telefonía Fija
        setupServiceButton(jButton4, "/Imagenes/Tel_Fij.png", "Telefonía Fija");
        jButton4.addActionListener(evt -> jButton4ActionPerformed(evt));
        backgroundPanel.add(jButton4);
        jLabel4.setFont(new Font("Segoe UI", Font.BOLD, 16)); // Fuente para etiqueta
        jLabel4.setForeground(new Color(30, 50, 70)); // Texto azul oscuro
        jLabel4.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel4.setText("Telefonía Fija"); // Texto más formal
        backgroundPanel.add(jLabel4);

        // Telefonía Móvil
        setupServiceButton(jButton7, "/Imagenes/Telefonía movil.png", "Telefonía Móvil");
        jButton7.addActionListener(evt -> jButton7ActionPerformed(evt));
        backgroundPanel.add(jButton7);
        jLabel3.setFont(new Font("Segoe UI", Font.BOLD, 16));
        jLabel3.setForeground(new Color(30, 50, 70)); // Texto azul oscuro
        jLabel3.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel3.setText("Telefonía Móvil"); // Texto más formal
        backgroundPanel.add(jLabel3);

        // Televisión
        setupServiceButton(jButton8, "/Imagenes/televisión.png", "Televisión Digital"); // Fallback text
        jButton8.addActionListener(evt -> jButton8ActionPerformed(evt));
        backgroundPanel.add(jButton8);
        jLabel5.setFont(new Font("Segoe UI", Font.BOLD, 16));
        jLabel5.setForeground(new Color(30, 50, 70)); // Texto azul oscuro
        jLabel5.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel5.setText("Televisión"); // Texto más formal
        backgroundPanel.add(jLabel5);

        // Internet
        setupServiceButton(jButton9, "/Imagenes/Wifi.png", "Conectividad a Internet"); // Fallback text
        jButton9.addActionListener(evt -> jButton9ActionPerformed(evt));
        backgroundPanel.add(jButton9);
        jLabel6.setFont(new Font("Segoe UI", Font.BOLD, 16));
        jLabel6.setForeground(new Color(30, 50, 70)); // Texto azul oscuro
        jLabel6.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel6.setText("Internet"); // Texto más formal
        backgroundPanel.add(jLabel6);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Método auxiliar para configurar botones de servicio
    private void setupServiceButton(JButton button, String imagePath, String fallbackText) {
        try {
            ImageIcon serviceIcon = new ImageIcon(getClass().getResource(imagePath));
            if (serviceIcon.getImageLoadStatus() == MediaTracker.COMPLETE) {
                Image img = serviceIcon.getImage();
                Image scaledImg = img.getScaledInstance(120, 120, Image.SCALE_SMOOTH); // Escalar icono
                button.setIcon(new ImageIcon(scaledImg));
            } else {
                logger.log(Level.WARNING, "Imagen '{0}' no encontrada. Usando texto de marcador para el botón.", imagePath);
                button.setText(fallbackText);
            }
        } catch (Exception e) {
            logger.log(Level.WARNING, "Error al cargar la imagen '{0}': {1}", new Object[]{imagePath, e.getMessage()});
            button.setText(fallbackText);
        }
        button.setContentAreaFilled(false);
        button.setBorderPainted(false);
        button.setFocusPainted(false);
        button.setHorizontalTextPosition(SwingConstants.CENTER);
        button.setVerticalTextPosition(SwingConstants.BOTTOM);
        button.setFont(new Font("Segoe UI", Font.BOLD, 14));
        button.setForeground(new Color(30, 50, 70)); // Texto azul oscuro para botones
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
        if (parentFrame != null) {
            parentFrame.setVisible(true);
        }
    }

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
        // Lógica para el botón de Televisión
        Television televisionFrame = new Television(this);
        televisionFrame.setVisible(true);
        this.dispose();
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        // Lógica para el botón de Telefonía Fija
        TeleFija teleFijaFrame = new TeleFija(this);
        teleFijaFrame.setVisible(true);
        this.dispose();
    }

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
        // Lógica para el botón de Telefonía Móvil
        TeleMovil teleMovilFrame = new TeleMovil(this);
        teleMovilFrame.setVisible(true);
        this.dispose();
    }

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
        // Lógica para el botón de Internet
        Internet internetFrame = new Internet(this); // Pasa la instancia actual de Servicios
        internetFrame.setVisible(true);
        this.dispose(); // Ocultar la ventana actual (Servicios)
    }

    /**
     * Adjusts the position and size of components when the frame is resized.
     */
    private void adjustComponentPositions() {
        int newWidth = getContentPane().getWidth();
        int newHeight = getContentPane().getHeight();

        // Título "PORTAFOLIO DE SERVICIOS"
        int titleWidth = newWidth - 100; // Mantener el ancho dinámico
        jLabel1.setBounds(50, 80, titleWidth, 40); // Mover más abajo a Y=80

        // Botón Regresar (más grande y más a la esquina)
        int regresarButtonWidth = 240; // Más grande
        int regresarButtonHeight = 65; // Más grande
        jButton1.setBounds(10, 10, regresarButtonWidth, regresarButtonHeight); // Más cerca de la esquina

        // Posicionamiento de los botones de servicio en una cuadrícula
        int buttonSize = 150; // Tamaño del área del botón (icono + texto)
        int buttonIconSize = 120; // Tamaño del icono dentro del botón
        int horizontalGap = 60; // Espacio horizontal entre botones
        int verticalGap = 40; // Espacio vertical entre filas de botones

        int totalRowWidth = (2 * buttonSize) + horizontalGap;
        int startX = (newWidth - totalRowWidth) / 2;
        int startY = jLabel1.getY() + jLabel1.getHeight() + 30; // Debajo del título, con un espacio de 30px

        // Primera fila: Internet y Televisión
        // Internet
        jButton9.setBounds(startX, startY, buttonSize, buttonSize + 30); // +30 para el texto
        jLabel6.setBounds(startX, startY + buttonSize, buttonSize, 20); // Etiqueta debajo del botón

        // Televisión
        jButton8.setBounds(startX + buttonSize + horizontalGap, startY, buttonSize, buttonSize + 30);
        jLabel5.setBounds(startX + buttonSize + horizontalGap, startY + buttonSize, buttonSize, 20);

        // Segunda fila: Telefonía Móvil y Telefonía Fija
        startY += buttonSize + 30 + verticalGap; // Mover hacia abajo para la siguiente fila
        // Telefonía Móvil
        jButton7.setBounds(startX, startY, buttonSize, buttonSize + 30);
        jLabel3.setBounds(startX, startY + buttonSize, buttonSize, 20);

        // Telefonía Fija
        jButton4.setBounds(startX + buttonSize + horizontalGap, startY, buttonSize, buttonSize + 30);
        jLabel4.setBounds(startX + buttonSize + horizontalGap, startY + buttonSize, buttonSize, 20);

        backgroundPanel.revalidate();
        backgroundPanel.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Servicios(null).setVisible(true));
    }
}
