/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_CHIDO;

import Clases.BackgroundPanel;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.MediaTracker;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.logging.Level;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author ASUS
 */
public class Television extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Television.class.getName());
    private JFrame parentFrame;

    // Componentes de la interfaz de usuario
    private BackgroundPanel backgroundPanel;
    private javax.swing.JButton jButton1; // Plan Estándar
    private javax.swing.JButton jButton2; // Regresar
    private javax.swing.JButton jButton3; // Plan Básico
    private javax.swing.JButton jButton4; // Plan Ultra
    private javax.swing.JLabel jLabel1; // Título "¡Tu próxima gran experiencia..."
    private javax.swing.JLabel jLabel10; // "Contenido actualizado..."
    private javax.swing.JLabel jLabel11; // "Instalación rápida..."
    private javax.swing.JLabel jLabel12; // "Infraestructura moderna..."
    private javax.swing.JLabel jLabel2; // "...comienza seleccionando el plan ideal!"
    private javax.swing.JLabel jLabel3; // "Más canales, más entretenimiento..."
    private javax.swing.JLabel jLabel4; // "Todos nuestros planes incluyen:"
    private javax.swing.JLabel jLabel5; // "Señal digital HD..."
    private javax.swing.JLabel jLabel6; // "App para ver TV..."
    private javax.swing.JLabel jLabel7; // "Graba y retrocede..."
    private javax.swing.JLabel jLabel8; // "Promociones exclusivas..."
    private javax.swing.JLabel jLabel9; // "Calidad de imagen HD y 4K..."

    /**
     * Creates new form Television
     */
    public Television() {
        initComponents();
        this.setSize(800, 750); // Ajustar tamaño
        this.setLocationRelativeTo(null); // Centrar

        // Add ComponentListener for responsiveness
        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                adjustComponentPositions();
            }
        });

        adjustComponentPositions(); // Ajustar posiciones inicialmente
    }

    public Television(JFrame parentFrame) {
        this(); // Llama al constructor sin argumentos para inicializar componentes
        this.parentFrame = parentFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        // Inicialización del BackgroundPanel como content pane
        backgroundPanel = new BackgroundPanel("/Imagenes/fondo.png");
        backgroundPanel.setLayout(null); // Usamos un layout nulo para posicionamiento absoluto
        this.setContentPane(backgroundPanel); // Establecer como content pane

        // Inicialización de componentes (ahora se añadirán a backgroundPanel)
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Planes de Televisión");

        // Botón Regresar
        jButton2.setBackground(new Color(90, 150, 200)); // Azul suave
        jButton2.setFont(new Font("Segoe UI", Font.BOLD, 22)); // Fuente más grande
        jButton2.setForeground(Color.WHITE);
        
        // Cargar y escalar el icono si existe
        try {
            ImageIcon atrasIcon = new ImageIcon(getClass().getResource("/Imagenes/Atras.png"));
            if (atrasIcon.getImageLoadStatus() == MediaTracker.COMPLETE) {
                Image img = atrasIcon.getImage();
                Image scaledImg = img.getScaledInstance(50, 50, Image.SCALE_SMOOTH); // Escalar icono más grande
                jButton2.setIcon(new ImageIcon(scaledImg));
            } else {
                logger.log(Level.WARNING, "Imagen 'Atras.png' no encontrada. Usando solo texto para el botón Regresar.");
            }
        } catch (Exception e) {
            logger.log(Level.WARNING, "Error al cargar la imagen 'Atras.png': " + e.getMessage());
        }
        
        jButton2.setText("Regresar");
        jButton2.setContentAreaFilled(false);
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(evt -> jButton2ActionPerformed(evt));
        backgroundPanel.add(jButton2);

        // Títulos principales
        jLabel1.setFont(new Font("Segoe UI", Font.BOLD, 30));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¡Tu próxima gran experiencia ");
        jLabel1.setForeground(new Color(30, 50, 70));
        backgroundPanel.add(jLabel1);

        jLabel2.setFont(new Font("Segoe UI", Font.BOLD, 30));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("comienza seleccionando el plan ideal!");
        jLabel2.setForeground(new Color(30, 50, 70));
        backgroundPanel.add(jLabel2);

        jLabel3.setFont(new Font("Segoe UI", Font.PLAIN, 20));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Más canales, más entretenimiento, mejor precio");
        jLabel3.setForeground(new Color(30, 50, 70));
        backgroundPanel.add(jLabel3);

        // Características de los planes
        jLabel4.setFont(new Font("Segoe UI", Font.BOLD, 16));
        jLabel4.setText("💡 Todos nuestros planes incluyen:");
        jLabel4.setForeground(new Color(30, 50, 70));
        backgroundPanel.add(jLabel4);

        jLabel5.setText("📡 Señal digital HD con excelente calidad de imagen y sonido");
        jLabel5.setForeground(new Color(30, 50, 70));
        backgroundPanel.add(jLabel5);

        jLabel6.setText("📱 App para ver TV desde tu celular, tablet o smart TV (sin costo adicional)");
        jLabel6.setForeground(new Color(30, 50, 70));
        backgroundPanel.add(jLabel6);

        jLabel7.setText("🔄 Graba y retrocede programas con funciones de \"TV en pausa\" (en planes seleccionados)");
        jLabel7.setForeground(new Color(30, 50, 70));
        backgroundPanel.add(jLabel7);

        jLabel8.setText("🎁 ¡Promociones exclusivas para nuevos clientes!");
        jLabel8.setForeground(new Color(30, 50, 70));
        backgroundPanel.add(jLabel8);

        jLabel9.setText("✅ Calidad de imagen HD y 4K según el plan que elijas");
        jLabel9.setForeground(new Color(30, 50, 70));
        backgroundPanel.add(jLabel9);

        jLabel10.setText("✅ Contenido actualizado y variedad para toda la familia ");
        jLabel10.setForeground(new Color(30, 50, 70));
        backgroundPanel.add(jLabel10);

        jLabel11.setText("✅ Instalación rápida y gratuita en la mayoría de planes");
        jLabel11.setForeground(new Color(30, 50, 70));
        backgroundPanel.add(jLabel11);

        jLabel12.setText("✅ Infraestructura moderna y cobertura nacional");
        jLabel12.setForeground(new Color(30, 50, 70));
        backgroundPanel.add(jLabel12);

        // Botones de planes (con carga de imagen robusta y estilo)
        setupPlanButton(jButton3, "/Imagenes/PBasico-removebg-preview.png", "Plan Básico TV"); // Usando PBasico como placeholder
        backgroundPanel.add(jButton3);

        setupPlanButton(jButton1, "/Imagenes/PEstandar-removebg-preview (1).png", "Plan Estándar TV"); // Usando PEstándar como placeholder
        backgroundPanel.add(jButton1);

        setupPlanButton(jButton4, "/Imagenes/PUltra-removebg-preview (1).png", "Plan Ultra TV"); // Usando PUltra como placeholder
        backgroundPanel.add(jButton4);

        pack();
    }

    // Método auxiliar para configurar botones de plan
    private void setupPlanButton(JButton button, String imagePath, String fallbackText) {
        try {
            ImageIcon planIcon = new ImageIcon(getClass().getResource(imagePath));
            if (planIcon.getImageLoadStatus() == MediaTracker.COMPLETE) {
                Image img = planIcon.getImage();
                Image scaledImg = img.getScaledInstance(180, 180, Image.SCALE_SMOOTH); // Escalar icono
                button.setIcon(new ImageIcon(scaledImg));
            } else {
                logger.log(Level.WARNING, "Imagen '{0}' no encontrada. Usando texto de marcador para el botón.", imagePath);
                button.setText(fallbackText);
            }
        } catch (Exception e) {
            logger.log(Level.WARNING, "Error al cargar la imagen '{0}': {1}", new Object[]{imagePath, e.getMessage()});
            button.setText(fallbackText);
        }
        button.setContentAreaFilled(false);
        button.setBorderPainted(false);
        button.setFocusPainted(false);
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
        if (parentFrame != null) {
            parentFrame.setVisible(true);
        }
    }

    private void adjustComponentPositions() {
        int newWidth = getContentPane().getWidth();
        int newHeight = getContentPane().getHeight();

        // Botón Regresar (más grande y más a la esquina)
        int regresarButtonWidth = 240;
        int regresarButtonHeight = 65;
        jButton2.setBounds(10, 10, regresarButtonWidth, regresarButtonHeight);

        // Títulos principales
        int titleWidth = newWidth - 100;
        jLabel1.setBounds(50, 90, titleWidth, 40);
        jLabel2.setBounds(50, jLabel1.getY() + jLabel1.getHeight(), titleWidth, 40);
        jLabel3.setBounds(50, jLabel2.getY() + jLabel2.getHeight() + 10, titleWidth, 30);

        // Características de los planes (ajustar posiciones y espaciado)
        int featureCol1X = 50;
        int featureCol2X = newWidth / 2 + 30;
        int featureStartY = jLabel3.getY() + jLabel3.getHeight() + 30;
        int featureLineHeight = 28;

        jLabel4.setBounds(featureCol1X, featureStartY, 400, 20);
        jLabel5.setBounds(featureCol1X + 20, featureStartY + featureLineHeight, 300, 20);
        jLabel9.setBounds(featureCol2X, featureStartY + featureLineHeight, 300, 20);

        jLabel6.setBounds(featureCol1X + 20, featureStartY + (2 * featureLineHeight), 300, 20);
        jLabel10.setBounds(featureCol2X, featureStartY + (2 * featureLineHeight), 300, 20);

        jLabel7.setBounds(featureCol1X + 20, featureStartY + (3 * featureLineHeight), 380, 20);
        jLabel11.setBounds(featureCol2X, featureStartY + (3 * featureLineHeight), 300, 20);

        jLabel8.setBounds(featureCol1X + 20, featureStartY + (4 * featureLineHeight), 300, 20);
        jLabel12.setBounds(featureCol2X, featureStartY + (4 * featureLineHeight), 300, 20);

        // Botones de planes (centrados y espaciados)
        int planButtonWidth = 200;
        int planButtonHeight = 200;
        int planButtonY = featureStartY + (5 * featureLineHeight) + 50;

        int gapBetweenButtons = 40;
        int totalButtonsWidth = (3 * planButtonWidth) + (2 * gapBetweenButtons);
        int startX = (newWidth - totalButtonsWidth) / 2;

        jButton3.setBounds(startX, planButtonY, planButtonWidth, planButtonHeight); // Básico
        jButton1.setBounds(startX + planButtonWidth + gapBetweenButtons, planButtonY, planButtonWidth, planButtonHeight); // Estándar
        jButton4.setBounds(startX + (2 * planButtonWidth) + (2 * gapBetweenButtons), planButtonY, planButtonWidth, planButtonHeight); // Ultra

        backgroundPanel.revalidate();
        backgroundPanel.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Television().setVisible(true));
    }
}
