/*
 * Click nbproject://SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbproject://SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_CHIDO;

import javax.swing.JFrame;

/**
 *
 * @author ASUS
 */
public class TeleMovil extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TeleMovil.class.getName());
    private JFrame parentFrame;

    /**
     * Creates new form TeleMovil
     */
    public TeleMovil() {
        initComponents();
    }

    public TeleMovil(JFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLayout(null);

        jLabel5.setText("🚀 Red 4G LTE (y 5G donde esté disponible)");
        jLabel5.setBounds(41, 184, 249, 16);

        jLabel6.setText("📶 Cobertura nacional + Roaming inteligente");
        jLabel6.setBounds(41, 212, 261, 16);

        jLabel7.setText("🔒 Seguridad de navegación incluida");
        jLabel7.setBounds(41, 248, 347, 16);

        jLabel8.setText("🎁 Promociones exclusivas para nuevos usuarios");
        jLabel8.setBounds(41, 284, 274, 16);

        jLabel9.setText("✅ Cambios de plan cuando quieras, sin costo");
        jLabel9.setBounds(462, 184, 299, 16);

        jButton2.setBackground(new java.awt.Color(248, 243, 243));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 36));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atras.png")));
        jButton2.setText("Regresar");
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(evt -> jButton2ActionPerformed(evt));
        jButton2.setBounds(21, 17, 263, 60);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¡Tu próxima gran experiencia ");
        jLabel1.setBounds(76, 91, 557, 48);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("comienza seleccionando el plan ideal!");
        jLabel2.setBounds(41, 139, 622, 48);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Plan_Smart-removebg-preview.png")));
        jButton1.setContentAreaFilled(false);
        jButton1.setBounds(62, 408, 213, 84);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Plan_Prepago-removebg-preview.png")));
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setBounds(258, 345, 197, 63);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Plan_Pro_Global-removebg-preview.png")));
        jButton4.setContentAreaFilled(false);
        jButton4.setBounds(525, 408, 218, 90);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Internet y comunicación en tu bolsillo, al mejor precio");
        jLabel3.setBounds(132, 187, 507, 25);

        jLabel4.setText("💡 Todos nuestros planes incluyen:");
        jLabel4.setBounds(41, 166, 192, 16);

        jLabel10.setText("✅ Sin contratos largos ni sorpresas en la factura");
        jLabel10.setBounds(462, 212, 299, 16);

        jLabel11.setText("✅ Soporte técnico por WhatsApp 24/7");
        jLabel11.setBounds(462, 248, 299, 16);

        jLabel12.setText("✅ Puedes conservar tu número actual (portabilidad gratis)");
        jLabel12.setBounds(447, 284, 314, 16);

        add(jLabel5);
        add(jLabel6);
        add(jLabel7);
        add(jLabel8);
        add(jLabel9);
        add(jButton2);
        add(jLabel1);
        add(jLabel2);
        add(jButton1);
        add(jButton3);
        add(jButton4);
        add(jLabel3);
        add(jLabel4);
        add(jLabel10);
        add(jLabel11);
        add(jLabel12);

        pack();
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
        if (parentFrame != null) {
            parentFrame.setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TeleMovil().setVisible(true));
    }

    // Variables declaration
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration
}