/*
 * Click nbproject://SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbproject://SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_CHIDO;

import javax.swing.JFrame;

/**
 *
 * @author ASUS
 */
public class Television extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Television.class.getName());
    private JFrame parentFrame;

    /**
     * Creates new form Television
     */
    public Television() {
        initComponents();
    }

    public Television(JFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLayout(null);

        jLabel5.setText("📡 Señal digital HD con excelente calidad de imagen y sonido");
        jLabel5.setBounds(21, 184, 350, 16);

        jLabel6.setText("📱 App para ver TV desde tu celular, tablet o smart TV (sin costo adicional)");
        jLabel6.setBounds(21, 218, 407, 16);

        jLabel7.setText("🔄 Graba y retrocede programas con funciones de \"TV en pausa\" (en planes seleccionados)");
        jLabel7.setBounds(21, 252, 462, 16);

        jLabel8.setText("🎁 ¡Promociones exclusivas para nuevos clientes!");
        jLabel8.setBounds(21, 286, 274, 16);

        jLabel9.setText("✅ Calidad de imagen HD y 4K según el plan que elijas");
        jLabel9.setBounds(462, 184, 299, 16);

        jButton2.setBackground(new java.awt.Color(248, 243, 243));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 36));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atras.png")));
        jButton2.setText("Regresar");
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(evt -> jButton2ActionPerformed(evt));
        jButton2.setBounds(21, 17, 263, 60);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¡Tu próxima gran experiencia ");
        jLabel1.setBounds(103, 77, 557, 48);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("comienza seleccionando el plan ideal!");
        jLabel2.setBounds(81, 125, 622, 48);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PEstandar-removebg-preview (1).png")));
        jButton1.setContentAreaFilled(false);
        jButton1.setBounds(45, 399, 213, 84);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PBasico-removebg-preview.png")));
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setBounds(395, 319, 214, 79);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PUltra-removebg-preview (1).png")));
        jButton4.setContentAreaFilled(false);
        jButton4.setBounds(510, 399, 218, 90);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Más canales, más entretenimiento, mejor precio");
        jLabel3.setBounds(154, 173, 507, 25);

        jLabel4.setText("💡 Todos nuestros planes incluyen:");
        jLabel4.setBounds(6, 166, 192, 16);

        jLabel10.setText("✅ Contenido actualizado y variedad para toda la familia ");
        jLabel10.setBounds(462, 218, 299, 16);

        jLabel11.setText("✅ Instalación rápida y gratuita en la mayoría de planes");
        jLabel11.setBounds(462, 252, 299, 16);

        jLabel12.setText("✅ Infraestructura moderna y cobertura nacional");
        jLabel12.setBounds(462, 286, 299, 16);

        add(jLabel5);
        add(jLabel6);
        add(jLabel7);
        add(jLabel8);
        add(jLabel9);
        add(jButton2);
        add(jLabel1);
        add(jLabel2);
        add(jButton1);
        add(jButton3);
        add(jButton4);
        add(jLabel3);
        add(jLabel4);
        add(jLabel10);
        add(jLabel11);
        add(jLabel12);

        pack();
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
        if (parentFrame != null) {
            parentFrame.setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Television().setVisible(true));
    }

    // Variables declaration
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration
}