/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_CHIDO;

/**
 *
 * @author ASUS
 */
public class User_1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(User_1.class.getName());

    /**
     * Creates new form User_1
     */
    public User_1() {
        initComponents();
        this.setLocationRelativeTo(null); // Center the frame
        this.setSize(600, 600); // Set a fixed size for the frame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null); // Changed from AbsoluteLayout

        jPanel1.setLayout(null); // Changed from AbsoluteLayout
        jPanel1.setBounds(0, 0, 600, 600); // Set bounds for jPanel1 to fill the frame

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Servicios_B-removebg-preview.png"))); // NOI18N
        jButton3.setText("jButton1");
        jButton3.setContentAreaFilled(false);
        jButton3.setBounds(60, 170, 190, 190); // Set bounds based on original AbsoluteConstraints
        // Add ActionListener for jButton3
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuario_B-removebg-preview.png"))); // NOI18N
        jButton5.setText("jButton1");
        jButton5.setContentAreaFilled(false);
        jButton5.setBounds(360, 160, 190, 190); // Set bounds based on original AbsoluteConstraints
        // Add ActionListener for jButton5
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Contratos_B-removebg-preview.png"))); // NOI18N
        jButton4.setText("jButton1");
        jButton4.setContentAreaFilled(false);
        jButton4.setBounds(210, 370, 190, 190); // Set bounds based on original AbsoluteConstraints
        // Add ActionListener for jButton4
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jLabel4.setFont(new java.awt.Font("ROG Fonts", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre del Usuario");
        jLabel4.setBounds(160, 100, 250, 30); // Set bounds, estimated size for text
        jPanel1.add(jLabel4);

        jLabel3.setFont(new java.awt.Font("ROG Fonts", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bienvenido");
        jLabel3.setBounds(90, 20, 390, 70); // Set bounds based on original AbsoluteConstraints
        jPanel1.add(jLabel3);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo_NetNexus-removebg-preview (1).png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBounds(450, 0, 180, 180); // Set bounds based on original AbsoluteConstraints
        jPanel1.add(jLabel2);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jLabel1.setBounds(0, 0, 600, 600); // Set bounds for background image to fill jPanel1
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1); // Added jPanel1 to content pane

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Abre la ventana de Servicios y oculta la actual (User_1)
        Servicios serviciosFrame = new Servicios(this);
        serviciosFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Abre la ventana de Perfil_User y oculta la actual (User_1)
        Perfil_User perfilUserFrame = new Perfil_User(this);
        perfilUserFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Abre la ventana de ContratosActivos y oculta la actual (User_1)
        ContratosActivos contratosActivosFrame = new ContratosActivos(this);
        contratosActivosFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new User_1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}