/*
 * Click nbproject://SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbproject://SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_CHIDO;

import javax.swing.JFrame;

/**
 *
 * @author ASUS
 */
public class Servicios extends javax.swing.JFrame {

    private JFrame parentFrame;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Servicios.class.getName());

    /**
     * Creates new form Servicios
     * @param parentFrame The parent JFrame to return to.
     */
    public Servicios(JFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(600, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 255));
        setForeground(java.awt.Color.white);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setFont(new java.awt.Font("ROG Fonts", 0, 48));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Servicios ");
        jLabel1.setBounds(30, 90, 530, 50);

        jButton1.setBackground(new java.awt.Color(248, 243, 243));
        jButton1.setFont(new java.awt.Font("ROG Fonts", 0, 18));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atras.png")));
        jButton1.setText("Regresar");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(evt -> jButton1ActionPerformed(evt));
        jButton1.setBounds(10, 20, 230, 60);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Tel_Fij.png")));
        jButton4.setText("jButton3");
        jButton4.addActionListener(evt -> jButton4ActionPerformed(evt));
        jButton4.setBounds(350, 410, 170, 160);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Telefonía movil.png")));
        jButton7.setText("jButton3");
        jButton7.setBounds(50, 410, 170, 160);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/televisión.png")));
        jButton8.setText("jButton3");
        jButton8.addActionListener(evt -> jButton8ActionPerformed(evt));
        jButton8.setBounds(350, 190, 170, 160);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Wifi.png")));
        jButton9.setText("jButton3");
        jButton9.setBounds(50, 190, 170, 160);

        jLabel3.setFont(new java.awt.Font("ROG Fonts", 0, 18));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Telefonia movil");
        jLabel3.setBounds(50, 380, 150, 24);

        jLabel4.setFont(new java.awt.Font("ROG Fonts", 0, 18));
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Telefonia Fija");
        jLabel4.setBounds(350, 380, 150, 24);

        jLabel5.setFont(new java.awt.Font("ROG Fonts", 0, 18));
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Television");
        jLabel5.setBounds(350, 160, 120, 24);

        jLabel6.setFont(new java.awt.Font("ROG Fonts", 0, 18));
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Internet");
        jLabel6.setBounds(50, 160, 100, 24);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png")));
        jLabel2.setBounds(0, 0, 600, 600);

        jPanel1.add(jLabel1);
        jPanel1.add(jButton1);
        jPanel1.add(jButton4);
        jPanel1.add(jButton7);
        jPanel1.add(jButton8);
        jPanel1.add(jButton9);
        jPanel1.add(jLabel3);
        jPanel1.add(jLabel4);
        jPanel1.add(jLabel5);
        jPanel1.add(jLabel6);
        jPanel1.add(jLabel2);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 602, 600);

        pack();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
        if (parentFrame != null) {
            parentFrame.setVisible(true);
        }
    }

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Servicios(null).setVisible(true));
    }

    // Variables declaration
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration
}